# Generated by Django 4.1.4 on 2022-12-24 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descrpción"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Precio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba",
                "verbose_name_plural": "Pruebas",
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descripción"),
                ),
                (
                    "mandatory_declaration",
                    models.BooleanField(
                        default=False, verbose_name="Declaración obligatoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfermedad",
                "verbose_name_plural": "Enfermedades",
            },
        ),
        migrations.CreateModel(
            name="Hospitalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "hospitalization_type",
                    models.IntegerField(
                        choices=[(1, "Cirugía"), (2, "Urgencia")],
                        default=0,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Precio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalización",
                "verbose_name_plural": "Hospitalizaciones",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("kind", models.CharField(max_length=50, verbose_name="Especie")),
                ("breed", models.CharField(max_length=30, verbose_name="Raza")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Hembra")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Fecha de Nacimiento")),
                (
                    "death_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fallecimiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
            },
        ),
        migrations.CreateModel(
            name="Proprietor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=50, verbose_name="Apellido")),
                ("address", models.CharField(max_length=100, verbose_name="Dirección")),
                ("phone", models.CharField(max_length=12, verbose_name="Teléfono")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Propieario",
                "verbose_name_plural": "Propietarios",
            },
        ),
        migrations.CreateModel(
            name="Reception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                ("reason", models.CharField(max_length=50, verbose_name="Motivo")),
                (
                    "condition",
                    models.CharField(max_length=50, verbose_name="Condición"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_of",
                        to="clinic.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepción",
                "verbose_name_plural": "Recepciones",
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descripción"),
                ),
                (
                    "treatment_type",
                    models.IntegerField(
                        choices=[(0, "Opcional"), (1, "Obliagtorio")],
                        default=0,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Precio"
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (0, "No aplica"),
                            (1, "Diario"),
                            (2, "Semanal"),
                            (3, "Mensual"),
                            (4, "Bimestral"),
                            (5, "Trimestral"),
                            (6, "Semestral"),
                            (7, "Anual"),
                        ],
                        default=0,
                        verbose_name="Periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento",
                "verbose_name_plural": "Tratamientos",
            },
        ),
        migrations.CreateModel(
            name="TreatmentApplied",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_applied_type",
                    models.IntegerField(
                        choices=[(1, "Normal"), (2, "Urgente")],
                        default=1,
                        verbose_name="Tipo de tratamienio aplicado",
                    ),
                ),
                (
                    "treatment_appied_date",
                    models.DateTimeField(verbose_name="Fecha de tratamiento aplicado"),
                ),
                (
                    "observation",
                    models.CharField(max_length=100, verbose_name="Observaciones"),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_for",
                        to="clinic.reception",
                    ),
                ),
                (
                    "veterinary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinay_perform",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento aplicado",
                "verbose_name_plural": "Tratamientos aplicados",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="proprietor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proprietor_of",
                to="clinic.proprietor",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "invoice_type",
                    models.IntegerField(
                        choices=[(1, "Normal"), (2, "Simplificada")],
                        default=1,
                        verbose_name="Tipo de factura",
                    ),
                ),
                ("pay_date", models.DateTimeField(verbose_name="Fecha de pago")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Total"
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_of",
                        to="clinic.reception",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
        migrations.CreateModel(
            name="Displacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "displacement_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de desplazamiento"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Precio"
                    ),
                ),
                (
                    "alternate_address",
                    models.CharField(max_length=100, verbose_name="Dirección alterna"),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_perform",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_with",
                        to="clinic.reception",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desplazamiento",
                "verbose_name_plural": "Desplazamientos",
            },
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnostic_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de diagnóstico"
                    ),
                ),
                ("result", models.CharField(max_length=100, verbose_name="Resultado")),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_of",
                        to="clinic.analysis",
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_in",
                        to="clinic.reception",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disgnóstico",
                "verbose_name_plural": "Diagnósticos",
            },
        ),
        migrations.CreateModel(
            name="OptionalTreatment",
            fields=[
                (
                    "treatment_applied",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="treatment_applied_for",
                        serialize=False,
                        to="clinic.treatmentapplied",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_with",
                        to="clinic.treatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento opcional",
                "verbose_name_plural": "Tratamientos opcionales",
            },
        ),
        migrations.CreateModel(
            name="MandatoryTreatment",
            fields=[
                (
                    "treatment_applied",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="treatment_applied_is",
                        serialize=False,
                        to="clinic.treatmentapplied",
                    ),
                ),
                ("drug", models.CharField(max_length=30, verbose_name="Fármaco")),
                ("drug_serial", models.CharField(max_length=30, verbose_name="Serie")),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_is",
                        to="clinic.treatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento obligatorio",
                "verbose_name_plural": "Tratamientos obligatorios",
            },
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "reception",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="reception_to",
                        serialize=False,
                        to="clinic.reception",
                    ),
                ),
                (
                    "initial_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de ingreso"
                    ),
                ),
                ("final_date", models.DateTimeField(verbose_name="Fecha de egreso")),
                ("room", models.CharField(max_length=30, verbose_name="Habitáculo")),
                (
                    "hospitalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalization_for",
                        to="clinic.hospitalization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internado",
                "verbose_name_plural": "Internados",
            },
        ),
        migrations.CreateModel(
            name="DicoverDesease",
            fields=[
                (
                    "diagnostic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="diagnostic_for",
                        serialize=False,
                        to="clinic.diagnostic",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_discovered",
                        to="clinic.disease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertencia de enfermedad",
                "verbose_name_plural": "Advertencias de enfermedad",
            },
        ),
    ]
