# Generated by Django 4.1.4 on 2022-12-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_rename_dicoverdesease_dicoverdisease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="treatment_type",
            field=models.IntegerField(
                choices=[(0, "Opcional"), (1, "Obligatorio")],
                default=0,
                verbose_name="Tipo",
            ),
        ),
    ]
