# Generated by Django 4.1.4 on 2023-05-26 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0004_alter_analysis_price_alter_hospitalization_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treatmentapplied",
            old_name="treatment_appied_date",
            new_name="treatment_applied_date",
        ),
    ]
